version: '3'
services:
  client:
    container_name: "mediadiary-client"
    image: mediadiary-client:latest
    env_file: ".env"
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        window: 120s
    ports:
      - "${CLIENTPORT}:80"
  server:
    container_name: "mediadiary-server"
    image: mediadiary-server:latest
    env_file: ".env"
    deploy:
      restart_policy:
        condition: any 
        delay: 10s
        window: 120s
    ports:
      - "${SERVERPORT}:5000"
  database:
    image: postgres:13-alpine
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123456
        ports:
            - 5432:5432
networks:
    default:
        external:
            name: mediadiary-network