version: '3'
services:
  client:
    container_name: "mediadiary-client"
    image: mediadiary-client:latest
    env_file: ".env"
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        window: 120s
    ports:
      - "${CLIENTPORT}:80"
  server:
    container_name: "mediadiary-server"
    image: mediadiary-server:latest
    env_file: ".env"
    deploy:
      restart_policy:
        condition: any 
        delay: 10s
        window: 120s
    ports:
      - "${SERVERPORT}:5000"